// api
export * from './metamodel/impl/metamodel-helpers.js';
export * from './metamodel/types/Disposable.js';
export * from './metamodel/types/Notification.js';
export * from './metamodel/types/EAnnotation.js';
export * from './metamodel/types/EStringToStringMapEntry.js';
export * from './metamodel/types/TypeScriptClass.js';
export * from './metamodel/types/EEnumerator.js';
export * from './metamodel/impl/EStringToStringMapEntryImpl.js';
export * from './metamodel/types/EAttribute.js';
export * from './metamodel/types/EClass.js';
export * from './metamodel/types/EClassifier.js';
export * from './metamodel/types/EDataType.js';
export * from './metamodel/types/EEnumLiteral.js';
export * from './metamodel/types/EGenericType.js';
export * from './metamodel/types/EEnum.js';
export * from './metamodel/types/EFactory.js';
export * from './metamodel/types/EList.js';
export * from './metamodel/types/EModelElement.js';
export * from './metamodel/types/ENamedElement.js';
export * from './metamodel/types/EObject.js';
export * from './metamodel/types/EOperation.js';
export * from './metamodel/types/EPackage.js';
export * from './metamodel/types/EParameter.js';
export * from './metamodel/types/EReference.js';
export * from './metamodel/types/EStructuralFeature.js';
export * from './metamodel/types/ETypeParameter.js';
export * from './metamodel/types/ETypedElement.js';

// impl
export * from './metamodel/impl/BasicEList.js';
export * from './metamodel/impl/DynamicEObjectImpl.js';
export * from './metamodel/impl/DynamicEFactoryImpl.js';
export * from './metamodel/impl/EAnnotationImpl.js';
export * from './metamodel/impl/EAttributeImpl.js';
export * from './metamodel/impl/EClassImpl.js';
export * from './metamodel/impl/EClassifierImpl.js';
export * from './metamodel/impl/EDataTypeImpl.js';
export * from './metamodel/impl/EEnumImpl.js';
export * from './metamodel/impl/EEnumLiteralImpl.js';
export * from './metamodel/impl/EFactoryImpl.js';
export * from './metamodel/impl/EGenericTypeImpl.js';
export * from './metamodel/impl/EModelElementImpl.js';
export * from './metamodel/impl/ENamedElementImpl.js';
export * from './metamodel/impl/EObjectImpl.js';
export * from './metamodel/impl/EOperationImpl.js';
export * from './metamodel/impl/EPackageImpl.js';
export * from './metamodel/impl/EParameterImpl.js';
export * from './metamodel/impl/EReferenceImpl.js';
export * from './metamodel/impl/EStructuralFeatureImpl.js';
export * from './metamodel/impl/ETypeParameterImpl.js';
export * from './metamodel/impl/ETypedElementImpl.js';

// registry
export * from './registry/epackage-registry.js';
export * from './registry/epackage-registry-impl.js';

// resource
export * from './resource/diagnostic.js';
export * from './resource/eobject-address.js';
export * from './resource/proxy.js';
export * from './resource/resource.js';
export * from './resource/resource-factory.js';
export * from './resource/resource-factory-registry.js';
export * from './resource/resource-factory-registry-impl.js';
export * from './resource/resource-impl.js';
export * from './resource/resource-set.js';
export * from './resource/resource-set-impl.js';
export * from './resource/resource-utils.js';
export * from './resource/serializer.js';
export * from './resource/uri.js';
export * from './resource/uri-converter.js';
export * from './resource/uri-converter-registry.js';
export * from './resource/uri-converter-registry-impl.js';
export * from './metamodel/EcorePackage.js';
export * from './metamodel/EcoreFactory.js';
export * from './metamodel/impl/EcorePackageImpl.js';
export * from './metamodel/impl/EcoreFactoryImpl.js';
export * from './metamodel/util/EcoreTypeGuards.js';
